print("Cześć, użytkowniku")
colour = input("Podaj swój ulubiony kolor")
print(f"Twój ulubiuony kolor to: {colour}")
print("Długość słowa: {0} wynosi {1}".format(colour, len(colour)))
print(f"Typ zmiennej koloru to: {type(colour)}")